#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

POWERLEVEL9K_MODE='awesome-fontconfig'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH="/usr/local/opt/php@7.1/bin:/usr/local/opt/php@7.1/sbin:$HOME/.composer/vendor/bin:$HOME/.bin:$PATH"

alias px="phpunit --testdox -v"
alias pa="php artisan"
alias pwm="watchman-make -p '**/*.php' --make=\"clear && printf '\e[3J' && vendor/bin/phpunit\" -t"

alias pg_start="launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
alias pg_stop="launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"

alias sphpini='subl /usr/local/etc/php/7.1/php.ini'
# gem install colorls
alias lc='colorls'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\n"
# POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="↳> "
POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(icons_test)
DEFAULT_USER="lucian"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
# extras: battery public_ip
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time time)

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
test -e "${HOME}/Settings/aliases.zsh" && source "${HOME}/Settings/aliases.zsh"

export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
