#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

POWERLEVEL9K_MODE='awesome-fontconfig'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH="/usr/local/opt/php@7.1/bin:/usr/local/opt/php@7.1/sbin:$HOME/.composer/vendor/bin:$HOME/.bin:$PATH"

alias px="phpunit --testdox"
alias pa="php artisan"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\n"
# POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="↳> "
POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(icons_test)
DEFAULT_USER="lucian"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
# extras: battery public_ip
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time time)
